version: "3.9"

services:
  registry:
    build: ./registry
    container_name: registry
    ports:
      - "8761:8761"
    networks:
      - school-net

  alumno:
    build: ./Alumno
    container_name: ms-alumnos
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry
    networks:
      - school-net

  cursos:
    build: ./Cursos
    container_name: ms-cursos
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry
    networks:
      - school-net

  administracion:
    build: ./Administracion
    container_name: ms-administracion
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry
    networks:
      - school-net

  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry
      - alumno
      - cursos
      - administracion
    networks:
      - school-net

networks:
  school-net:
    driver: bridge