spring:
  application:
    name: gateway
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev
    import: "configserver:http://localhost:8888"

---
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://configserver:8888"
