server:
  port: 8083

spring:
  application:
    name: ms-administracion

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
