spring:
  application:
    name: modulo-administracion
  profiles:
    default: dev
  config:
    import: "configserver:http://localhost:8888"

---
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://configserver:8888"